name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Test with Gradle
      run: ./gradlew test
    - name: Lint main module
      run: ./gradlew checkstyleMain
    - name: Lint test module
      run: ./gradlew checkstyleTest
    - name: Run test coverage
      run: ./gradlew jacocoTestCoverageVerification
